In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("../dataset/train.csv")

In [8]:
df.head()

,id,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,...,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,0,Loamy,4.92,32.58,1.01,3.05,15.01,50.61,725.99,5.90,...,Sugarcane,Sowing,Zaid,Drip,Rainwater,0.82,No,112.16,East,Low
1,1,Clay,7.08,56.61,0.44,2.00,22.92,67.86,985.66,6.98,...,Wheat,Vegetative,Kharif,Rainfed,River,5.27,Yes,47.16,South,Low
2,2,Clay,5.69,27.71,0.81,2.83,26.97,92.22,2201.70,6.05,...,Rice,Vegetative,Kharif,Sprinkler,Reservoir,8.24,Yes,110.38,North,Low
3,3,Sandy,5.65,13.32,1.33,0.87,13.32,61.57,1357.33,9.12,...,Wheat,Flowering,Kharif,Canal,River,8.32,Yes,53.85,South,Medium
4,4,Clay,7.96,59.14,0.38,0.96,20.22,91.11,1538.20,6.95,...,Wheat,Sowing,Rabi,Canal,River,7.37,No,93.19,South,Low

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 630000 entries, 0 to 629999
Data columns (total 21 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id                       630000 non-null  int64
 1   Soil_Type                630000 non-null  object
 2   Soil_pH                  630000 non-null  float64
 3   Soil_Moisture            630000 non-null  float64
 4   Organic_Carbon           630000 non-null  float64
 5   Electrical_Conductivity  630000 non-null  float64
 6   Temperature_C            630000 non-null  float64
 7   Humidity                 630000 non-null  float64
 8   Rainfall_mm              630000 non-null  float64
 9   Sunlight_Hours           630000 non-null  float64
 10  Wind_Speed_kmh           630000 non-null  float64
 11  Crop_Type                630000 non-null  object
 12  Crop_Growth_Stage        630000 non-null  object
 13  Season                   630000 non-null  object
 14  Irrigation_Type          630000 non-null  object
 15  Water_Source             630000 non-null  object
 16  Field_Area_hectare       630000 non-null  float64
 17  Mulching_Used            630000 non-null  object
 18  Previous_Irrigation_mm   630000 non-null  float64
 19  Region                   630000 non-null  object
 20  Irrigation_Need          630000 non-null  object
dtypes: float64(11), int64(1), object(9)
memory usage: 100.9+ MB

In [12]:
df['Rainfall_mm'].unique()

array([ 725.99,  985.66, 2201.7 , ..., 1022.42, 1130.21,  461.48],
      shape=(19308,))

In [12]:
df.describe()

,id,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Field_Area_hectare,Previous_Irrigation_mm
count,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000,630000.000000
mean,314999.500000,6.482497,37.304482,0.922858,1.744605,26.998166,61.563180,1462.207566,7.513382,10.375394,7.517745,62.318177
std,181865.479132,0.922504,16.377082,0.365808,0.952321,8.623621,19.708152,612.989738,1.999322,5.689458,4.218124,34.246939
min,0.000000,4.800000,8.000000,0.300000,0.100000,12.000000,25.000000,0.380000,4.000000,0.500000,0.300000,0.020000
25%,157499.750000,5.690000,23.340000,0.610000,0.930000,19.517500,45.390000,954.570000,5.760000,5.280000,3.880000,33.140000
50%,314999.500000,6.440000,37.750000,0.910000,1.740000,26.960000,61.650000,1467.160000,7.580000,10.480000,7.380000,61.150000
75%,472499.250000,7.270000,51.270000,1.220000,2.580000,34.540000,79.120000,2054.280000,9.250000,15.430000,11.140000,92.690000
max,629999.000000,8.200000,64.990000,1.600000,3.500000,42.000000,94.990000,2499.690000,11.000000,20.000000,15.000000,119.990000

In [13]:
df.columns

Index(['id', 'Soil_Type', 'Soil_pH', 'Soil_Moisture', 'Organic_Carbon',
       'Electrical_Conductivity', 'Temperature_C', 'Humidity', 'Rainfall_mm',
       'Sunlight_Hours', 'Wind_Speed_kmh', 'Crop_Type', 'Crop_Growth_Stage',
       'Season', 'Irrigation_Type', 'Water_Source', 'Field_Area_hectare',
       'Mulching_Used', 'Previous_Irrigation_mm', 'Region', 'Irrigation_Need'],
      dtype='object')

In [14]:
df = df.drop(columns=['id','Electrical_Conductivity','Season','Region','Water_Source'])

In [15]:
df.columns

Index(['Soil_Type', 'Soil_pH', 'Soil_Moisture', 'Organic_Carbon',
       'Temperature_C', 'Humidity', 'Rainfall_mm', 'Sunlight_Hours',
       'Wind_Speed_kmh', 'Crop_Type', 'Crop_Growth_Stage', 'Irrigation_Type',
       'Field_Area_hectare', 'Mulching_Used', 'Previous_Irrigation_mm',
       'Irrigation_Need'],
      dtype='object')

In [16]:
df.isnull().sum()

Soil_Type                 0
Soil_pH                   0
Soil_Moisture             0
Organic_Carbon            0
Temperature_C             0
Humidity                  0
Rainfall_mm               0
Sunlight_Hours            0
Wind_Speed_kmh            0
Crop_Type                 0
Crop_Growth_Stage         0
Irrigation_Type           0
Field_Area_hectare        0
Mulching_Used             0
Previous_Irrigation_mm    0
Irrigation_Need           0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df['Soil_Type'].unique()

array(['Loamy', 'Clay', 'Sandy', 'Silt'], dtype=object)

In [19]:
df['Crop_Growth_Stage'].unique()

array(['Sowing', 'Vegetative', 'Flowering', 'Harvest'], dtype=object)

In [20]:
df['Irrigation_Type'].value_counts()

Irrigation_Type
Canal        161901
Sprinkler    161400
Rainfed      155607
Drip         151092
Name: count, dtype: int64

In [21]:
df['Crop_Type'].value_counts()

Crop_Type
Sugarcane    108910
Rice         106697
Cotton       104645
Maize        104274
Wheat        103005
Potato       102469
Name: count, dtype: int64

In [22]:
df.select_dtypes(include="object").columns

Index(['Soil_Type', 'Crop_Type', 'Crop_Growth_Stage', 'Irrigation_Type',
       'Mulching_Used', 'Irrigation_Need'],
      dtype='object')

In [15]:
X = df.drop(columns='Irrigation_Need')
y = df['Irrigation_Need']

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test,y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [25]:
X.shape

(630000, 15)

In [26]:
y.shape

(630000,)

In [27]:
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer

ohe = OneHotEncoder(drop="if_binary", sparse_output=False)
ode = OrdinalEncoder()

ct = ColumnTransformer(
    transformers=[
        ("onehot", ohe, [
            "Soil_Type",
            "Crop_Type",
            "Irrigation_Type",
            "Mulching_Used"
        ]),
        ("ordinal", ode, [
            "Crop_Growth_Stage"
        ])
    ],
    remainder="passthrough"
)

ct.set_output(transform='pandas')

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehot',
                                 OneHotEncoder(drop='if_binary',
                                               sparse_output=False),
                                 ['Soil_Type', 'Crop_Type', 'Irrigation_Type',
                                  'Mulching_Used']),
                                ('ordinal', OrdinalEncoder(),
                                 ['Crop_Growth_Stage'])])

In [28]:
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier

pipeline = Pipeline([
    ("preprocessor", ct),
    ("classifier", DecisionTreeClassifier())
])

In [30]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehot',
                                                  OneHotEncoder(drop='if_binary',
                                                                sparse_output=False),
                                                  ['Soil_Type', 'Crop_Type',
                                                   'Irrigation_Type',
                                                   'Mulching_Used']),
                                                 ('ordinal', OrdinalEncoder(),
                                                  ['Crop_Growth_Stage'])])),
                ('classifier', DecisionTreeClassifier())])

In [ ]:
y_pred = pipeline.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test, y_pred)
cr = classification_report(y_test,y_pred)

print(f"accuracy : {accuracy} \n")
print(cm)
print("------------------- \n")
print(cr)

accuracy : 0.970515873015873

[[ 3799     0   450]
 [    1 72270  1466]
 [  518  1280 46216]]
-------------------

              precision    recall  f1-score   support

        High       0.88      0.89      0.89      4249
         Low       0.98      0.98      0.98     73737
      Medium       0.96      0.96      0.96     48014

    accuracy                           0.97    126000
   macro avg       0.94      0.95      0.94    126000
weighted avg       0.97      0.97      0.97    126000

In [31]:
from sklearn.ensemble import RandomForestClassifier

rf_pipeline = Pipeline([
    ("preprocessor",ct),
    ("classifier", RandomForestClassifier(random_state=42))
])

In [ ]:
rf_pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehot',
                                                  OneHotEncoder(drop='if_binary',
                                                                sparse_output=False),
                                                  ['Soil_Type', 'Crop_Type',
                                                   'Irrigation_Type',
                                                   'Mulching_Used']),
                                                 ('ordinal', OrdinalEncoder(),
                                                  ['Crop_Growth_Stage'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [ ]:
y_pred_rf = rf_pipeline.predict(X_test)

In [ ]:
print(accuracy_score(y_test,y_pred_rf))
print(f"\n {confusion_matrix(y_test,y_pred_rf)}")
print(classification_report(y_test,y_pred_rf))

0.9852142857142857

 [[ 3820     0   429]
 [    0 73420   317]
 [  110  1007 46897]]
              precision    recall  f1-score   support

        High       0.97      0.90      0.93      4249
         Low       0.99      1.00      0.99     73737
      Medium       0.98      0.98      0.98     48014

    accuracy                           0.99    126000
   macro avg       0.98      0.96      0.97    126000
weighted avg       0.99      0.99      0.99    126000

In [32]:
from sklearn.model_selection import RandomizedSearchCV

param_distributions = {
    "classifier__n_estimators": [100, 200, 300],
    "classifier__max_depth": [10, 20, None],
    "classifier__min_samples_split": [2, 5],
    "classifier__min_samples_leaf": [1, 2],
    "classifier__max_features": ["sqrt", "log2"]
}

random_search = RandomizedSearchCV(
    estimator=rf_pipeline,
    param_distributions=param_distributions,
    n_iter=5,
    cv=3,
    scoring="accuracy",
    random_state=42,
    n_jobs=2,
    verbose=2
)

In [33]:
random_search.fit(X_train, y_train)

Fitting 3 folds for each of 5 candidates, totalling 15 fits

RandomizedSearchCV(cv=3,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(remainder='passthrough',
                                                                transformers=[('onehot',
                                                                               OneHotEncoder(drop='if_binary',
                                                                                             sparse_output=False),
                                                                               ['Soil_Type',
                                                                                'Crop_Type',
                                                                                'Irrigation_Type',
                                                                                'Mulching_Used']),
                                                                              ('ordinal',
                                                                               OrdinalEncoder(),
                                                                               ['Crop_Growth_Stage'])])),
                                             ('classifier',
                                              RandomForestClassifier(random_state=42))]),
                   n_iter=5, n_jobs=2,
                   param_distributions={'classifier__max_depth': [10, 20, None],
                                        'classifier__max_features': ['sqrt',
                                                                     'log2'],
                                        'classifier__min_samples_leaf': [1, 2],
                                        'classifier__min_samples_split': [2, 5],
                                        'classifier__n_estimators': [100, 200,
                                                                     300]},
                   random_state=42, scoring='accuracy', verbose=2)

In [38]:
y_pred_rf_v2 = random_search.predict(X_test)

In [44]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
# accuracy_rf = accuracy_score(y_test,y_pred_rf_v2)
# print(accuracy_rf)
cm = confusion_matrix(y_test,y_pred_rf_v2)
accuracy = accuracy_score(y_test, y_pred_rf_v2)
cr = classification_report(y_test,y_pred_rf_v2)

print(f"accuracy : {accuracy} \n")
print(cm)
print("------------------- \n")
print(cr)

accuracy : 0.9851904761904762

[[ 3809     0   440]
 [    0 73421   316]
 [  107  1003 46904]]
-------------------

              precision    recall  f1-score   support

        High       0.97      0.90      0.93      4249
         Low       0.99      1.00      0.99     73737
      Medium       0.98      0.98      0.98     48014

    accuracy                           0.99    126000
   macro avg       0.98      0.96      0.97    126000
weighted avg       0.99      0.99      0.99    126000

In [41]:
random_search.best_params_

{'classifier__n_estimators': 200,
 'classifier__min_samples_split': 5,
 'classifier__min_samples_leaf': 1,
 'classifier__max_features': 'sqrt',
 'classifier__max_depth': 20}

In [45]:
random_search.best_score_
best_model = random_search.best_estimator_

In [47]:
import joblib
joblib.dump(best_model,"irrigation_pipeline.pkl" )

['irrigation_pipeline.pkl']

In [1]:
import joblib

pipeline = joblib.load("irrigation_pipeline.pkl")

In [3]:
rf = pipeline.named_steps["classifier"]
rf.feature_importances_

array([0.00067714, 0.00065976, 0.0006728 , 0.00065693, 0.00060585,
       0.00066737, 0.00063015, 0.00066943, 0.00066752, 0.00060206,
       0.00079508, 0.00060547, 0.0006342 , 0.00062948, 0.10032693,
       0.30634993, 0.00692089, 0.28161916, 0.00623155, 0.10297283,
       0.01033682, 0.03949084, 0.00684198, 0.11044354, 0.00714605,
       0.01214623])

In [4]:
feature_names = pipeline.named_steps["preprocessor"].get_feature_names_out()

In [5]:
import pandas as pd

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": rf.feature_importances_
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
)

print(importance_df)

                              Feature  Importance
15         ordinal__Crop_Growth_Stage    0.306350
17           remainder__Soil_Moisture    0.281619
23          remainder__Wind_Speed_kmh    0.110444
19           remainder__Temperature_C    0.102973
14          onehot__Mulching_Used_Yes    0.100327
21             remainder__Rainfall_mm    0.039491
25  remainder__Previous_Irrigation_mm    0.012146
20                remainder__Humidity    0.010337
24      remainder__Field_Area_hectare    0.007146
16                 remainder__Soil_pH    0.006921
22          remainder__Sunlight_Hours    0.006842
18          remainder__Organic_Carbon    0.006232
10      onehot__Irrigation_Type_Canal    0.000795
0              onehot__Soil_Type_Clay    0.000677
2             onehot__Soil_Type_Sandy    0.000673
7              onehot__Crop_Type_Rice    0.000669
8         onehot__Crop_Type_Sugarcane    0.000668
5             onehot__Crop_Type_Maize    0.000667
1             onehot__Soil_Type_Loamy    0.000660
3              onehot__Soil_Type_Silt    0.000657
12    onehot__Irrigation_Type_Rainfed    0.000634
6            onehot__Crop_Type_Potato    0.000630
13  onehot__Irrigation_Type_Sprinkler    0.000629
4            onehot__Crop_Type_Cotton    0.000606
11       onehot__Irrigation_Type_Drip    0.000605
9             onehot__Crop_Type_Wheat    0.000602

In [17]:
from sklearn.inspection import permutation_importance

result = permutation_importance(
    pipeline,
    X_test,
    y_test,
    n_repeats=10,
    random_state=42,
    scoring="accuracy"
)

perm_df = pd.DataFrame({
    "Feature": X_test.columns,
    "Importance": result.importances_mean
}).sort_values("Importance", ascending=False)

print(perm_df)

                    Feature  Importance
12        Crop_Growth_Stage    0.237748
3             Soil_Moisture    0.219623
17            Mulching_Used    0.118355
10           Wind_Speed_kmh    0.115773
6             Temperature_C    0.113263
8               Rainfall_mm    0.022258
7                  Humidity    0.000108
18   Previous_Irrigation_mm    0.000051
11                Crop_Type    0.000035
14          Irrigation_Type    0.000020
4            Organic_Carbon    0.000010
13                   Season    0.000000
15             Water_Source    0.000000
0                        id    0.000000
5   Electrical_Conductivity    0.000000
19                   Region    0.000000
16       Field_Area_hectare   -0.000002
1                 Soil_Type   -0.000013
2                   Soil_pH   -0.000016
9            Sunlight_Hours   -0.000033